version: '3.0'

services:
  web:
    build: .
    image: franklinyu/ietf-draft-notifier
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres@db/main
      JWS_KEY:
      SMTP_SERVER:
      SMTP_PORT:
      SMTP_USERNAME:
      SMTP_PASSWORD:
      SMTP_SENDER_NAME:
      SMTP_SENDER_ADDRESS:
    ports:
      - '${PORT:-9292}:9292'
  db:
    image: postgres:11-alpine
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
